### ISSUE TITLE
Error in `httr2::req_perform()`: ! HTTP 400 Bad Request.

### ISSUE THREAD

**Issue by canng** [sachit27/greenR#4]
**Describe the bug**
The code 

```
bbox = c(10.781338, 106.686558, 10.771941, 106.698962)
data = get_osm_data(bbox) 
```

return 

> Error in `httr2::req_perform()`:
> ! HTTP 400 Bad Request.
> Run `rlang::last_trace()` to see where the error occurred.

With ```rlang::last_trace()``` returns 

> <error/httr2_http_400>
> Error in `httr2::req_perform()`:
> ! HTTP 400 Bad Request.
> ---
> Backtrace:
>     ▆
>  1. ├─greenR::get_osm_data(bbox)
>  2. │ └─... %>% osmdata::osmdata_sf()
>  3. └─osmdata::osmdata_sf(.)
>  4.   └─osmdata:::fill_overpass_data(obj, doc, quiet = quiet)
>  5.     └─osmdata:::overpass_query(...)
>  6.       └─httr2::req_perform(req)

**Comment by sachit27** [comment]
The error is due to the way how you specify the bounding box. The function expects the bounding box coordinates to be in the order: c(left, bottom, right, top), whereas in your query it is top, left, bottom, right.

To fix this, you need to reorder the coordinates to match the expected format. 
Try it like this : 
``
bbox = c(106.686558, 10.771941, 106.698962, 10.781338)
``
``
data = get_osm_data(bbox)
``
It will work.
